version: "3"

services:
  db:
    image: postgres:13-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"
  web:
    build: .
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py wait_for_db &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "18000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  celery:
    restart: always
    build:
      context: .
    command: celery -A theeyecore worker --loglevel=INFO
    volumes:
      - .:/app
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - rabbitmq
      - web


